// src/config.js
export const config = {
    javascript: [
      "What is closure in JavaScript?",
      "Explain prototypal inheritance.",
      "What is the difference between var, let, and const?",
      "How does this work in JavaScript?",
      "What are promises, and how do they work?",
      "Explain the event loop in JavaScript.",
      "What is the difference between == and ===?",
      "What are higher-order functions?",
      "What is a callback function?",
      "Explain the concept of hoisting.",
      "What is the difference between synchronous and asynchronous code?",
      "How do you manage state in JavaScript applications?",
      "What is the purpose of the bind, call, and apply methods?",
      "What are JavaScript modules and how do you use them?",
      "How does JavaScript handle errors?",
      "What is the purpose of Object.freeze?",
      "What are the differences between ES5 and ES6?",
      "Explain the prototype chain.",
      "What are Set and Map objects?",
      "How does garbage collection work in JavaScript?",
      "What is functional programming?",
      "How do you handle asynchronous operations in JavaScript?",
      "What is event delegation?",
      "Explain JavaScript's event propagation model.",
      "What are the different types of errors in JavaScript?",
      "What is the purpose of async and await?",
      "How can you create private variables in JavaScript?",
      "What are template literals?",
      "How do you use destructuring in JavaScript?",
      "What is the Spread Operator and how is it used?",
      "Explain the new keyword and how it works.",
      "What is the purpose of the Reflect API?",
      "How do you create and use JavaScript classes?",
      "What are the different types of functions in JavaScript?",
      "What is the purpose of the Symbol data type?",
      "What is the fetch API and how does it work?",
      "How do you use the import and export statements?",
      "What is the window object and what are its properties?",
      "Explain the difference between null and undefined.",
      "What are the benefits of using const over let?",
      "How do you debug JavaScript code?",
      "What is the purpose of Object.assign?",
      "What is the difference between Array.prototype.map and Array.prototype.forEach?",
      "How do you handle user input in JavaScript?",
      "What is a JavaScript generator function?",
      "How do you work with dates and times in JavaScript?",
      "What is the purpose of the Intl object in JavaScript?",
      "How does JavaScript handle concurrency?",
    ],
    react: [
      "What are hooks in React?",
      "Explain the virtual DOM.",
      "What is the purpose of useState?",
      "What is useEffect and how is it used?",
      "What is a React component?",
      "How do you handle state in class components vs functional components?",
      "What are controlled and uncontrolled components?",
      "How do you manage component lifecycle in React?",
      "What is context and how is it used?",
      "Explain the useReducer hook.",
      "What are error boundaries?",
      "How do you optimize performance in React applications?",
      "What is React.memo and when should you use it?",
      "How does React handle events?",
      "What is the purpose of useRef?",
      "How do you implement routing in React?",
      "What is React.lazy and Suspense?",
      "How do you handle forms in React?",
      "What is the difference between useCallback and useMemo?",
      "What is the key prop and why is it important?",
      "How do you pass data between components?",
      "What are higher-order components (HOCs)?",
      "What is the purpose of React.StrictMode?",
      "How do you perform server-side rendering with React?",
      "What is React Router and how is it used?",
      "How do you handle side effects in React?",
      "What are the different lifecycle methods in class components?",
      "How do you use PropTypes in React?",
      "What is useContext and how is it used?",
      "How do you implement lazy loading in React?",
      "What is a functional component?",
      "How does React.createContext work?",
      "What are React Fragments and why are they useful?",
      "How do you manage global state in React?",
      "What is the purpose of useLayoutEffect?",
      "How do you test React components?",
      "What is ReactDOM.render?",
      "How do you use React.createPortal?",
      "What are some common performance issues in React and how do you fix them?",
      "How do you manage API calls in React?",
      "What is React Query?",
      "How do you use refs in functional components?",
      "What is the difference between useEffect and useLayoutEffect?",
      "How do you handle asynchronous operations in React?",
      "What are some best practices for React development?",
      "How do you implement authentication in a React application?",
      "What are React Suspense and Error Boundaries?",
    ],
    html: [
      "What are semantic HTML elements?",
      "Explain the box model.",
      "What is the purpose of the head tag?",
      "How do you include external CSS and JavaScript in an HTML document?",
      "What is the difference between div and span?",
      "How do you create a form in HTML?",
      "What is the canvas element and how is it used?",
      "How do you use HTML5 to build a responsive web page?",
      "What are HTML attributes and how are they used?",
      "What is the difference between ol and ul?",
      "How do you include images in HTML?",
      "What is the purpose of the meta tag?",
      "How do you create tables in HTML?",
      "What are the different types of input elements in HTML forms?",
      "What is the iframe tag used for?",
      "How do you create a link in HTML?",
      "What are HTML entities and how are they used?",
      "What is the header element and what is its purpose?",
      "How do you use the audio and video elements?",
      "What are ARIA roles and attributes?",
      "How do you use HTML5 APIs like localStorage and sessionStorage?",
      "What is the purpose of the footer tag?",
      "How do you use HTML to create a navigation menu?",
      "What is the section tag used for?",
      "How do you define document structure using HTML5?",
      "What are the new input types introduced in HTML5?",
      "How do you use the article and aside elements?",
      "What is the main element and why is it important?",
      "How do you use the mark tag?",
      "What are the benefits of using dl for definition lists?",
      "How do you embed Google Maps in HTML?",
      "What is the button element and how is it different from input type='button'?",
      "How do you create a responsive grid layout in HTML?",
      "What is the purpose of the noscript tag?",
      "How do you use the details and summary elements?",
      "What are the different ways to include CSS in HTML?",
      "How do you use the progress element?",
      "What is the datalist element and how is it used?",
      "How do you create and use custom data attributes in HTML?",
      "What is the role of the figure and figcaption elements?",
      "How do you handle form validation in HTML5?",
      "What are the differences between HTML and XHTML?",
      "How do you include metadata in an HTML document?",
      "What is the role of the svg element in HTML?",
      "How do you create a web page layout using HTML5 semantic elements?",
      "What are the new features in HTML5 that enhance multimedia support?",
    ],
    css: [
      "What is Flexbox?",
      "Explain CSS Grid.",
      "What is the CSS box model?",
      "How do you center elements in CSS?",
      "What are pseudo-classes and pseudo-elements?",
      "How do you use CSS animations and transitions?",
      "What are media queries and how are they used?",
      "What is the difference between class and id selectors?",
      "How do you use CSS variables (custom properties)?",
      "What is the purpose of the display property?",
      "How do you implement responsive design in CSS?",
      "What are CSS preprocessors and how do they work?",
      "What is the difference between absolute, relative, fixed, and sticky positioning?",
      "How do you create a grid layout with CSS Grid?",
      "What are CSS Flexbox properties and how are they used?",
      "How do you style form elements in CSS?",
      "What is the :root pseudo-class?",
      "How do you implement a responsive typography system?",
      "What is the purpose of the z-index property?",
      "How do you create CSS hover effects?",
      "What are CSS transitions and how do you use them?",
      "How do you use @keyframes for animations?",
      "What is the purpose of the opacity property?",
      "How do you use CSS to hide elements visually but keep them accessible to screen readers?",
      "What are CSS Grid areas and how are they used?",
      "How do you create multi-column layouts with CSS?",
      "What are CSS filters and how are they used?",
      "How do you use the calc() function in CSS?",
      "What is the box-sizing property and why is it important?",
      "How do you style HTML tables with CSS?",
      "What is the transform property and how is it used?",
      "How do you use the :nth-child selector?",
      "What are CSS specificity rules?",
      "How do you handle cross-browser compatibility issues in CSS?",
      "What are CSS custom properties and how are they different from preprocessor variables?",
      "How do you create a CSS grid-based layout?",
      "What is the difference between a block-level element and an inline element?",
      "How do you use CSS to create a sticky header?",
      "What is the role of the @media rule in responsive design?",
      "How do you use CSS to create accessible and user-friendly designs?",
      "What are CSS pseudo-elements and how are they used?",
      "How do you use the :focus and :active pseudo-classes?",
      "What is the purpose of the content property in CSS?",
      "How do you create a CSS-only dropdown menu?",
      "What is the purpose of the font-family property?",
      "How do you use CSS to create a print-friendly stylesheet?",
      "What are some best practices for writing maintainable CSS?",
    ],
  };
